import "./globals.css";
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import '../components/Navbar/navbar.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-FiraSans bg-BodyBg min-h-screen antialiased">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}